### DISCUSSION TITLE
In over my head with gremlin / Java

### DISCUSSION THREAD

**Discussion by unimaginativeusername** [ArcadeData/arcadedb#1863] [Q&A]
I am trying to connect to a remote database:

Docker
```
services:
  arcadedb:
    ports:
      - 2480:2480
      - 8182:8182
      - 5432:5432
    environment:
      - JAVA_OPTS= -Darcadedb.server.rootPassword=playwithdata -Darcadedb.server.plugins=GremlinServer:com.arcadedb.server.gremlin.GremlinServerPlugin,Postgres:com.arcadedb.postgres.PostgresProtocolPlugin
    image: arcadedata/arcadedb:24.6.1
    container_name: arcadedb-public
    networks:
      - reverse-proxy
      - arcadedb

networks:
  reverse-proxy:
    external: true
  arcadedb:
```

Setting up the connection:
```
 ArcadeGraphFactory pool = ArcadeGraphFactory.withRemote(graphDbConfig.getHost(),
                    graphDbConfig.getHttpPort(),
                    graphDbConfig.getGraphName(),
                    graphDbConfig.getUser(),
                    graphDbConfig.getPassword());
```
Getting the graph:
` return pool.get();`

Using it:
```
 ArcadeGraph g = ConnectionPool.getGraph();
        List<? extends Vertex> accounts = g.traversal().V().hasLabel("Account").has("email", email).toList();
        g.close();
```

This works, as long as I create a DB called "graph". I have need now for using multiple schemas at the same time and would like to access them as above.

Calling the traversal results in
```
 Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: The traversal source [auth] for alias [g] is not configured on the server.] with root cause
org.apache.tinkerpop.gremlin.driver.exception.ResponseException: The traversal source [auth] for alias [g] is not configured on the server.
```

I suspect I need to change a server config? Is it at all possible to use multiple databases in parallel?

(Everything works in Studio; I can access both databases via Postgres driver, too, using the same config. Both databases - graph and auth - were created through studio on top of the Beer example.)

My setup is a bit Frankenstein'ed, but I think I have provided everything that matters for this issue; I use postgres solely to get Flyway to cooperate during boot.

Edit:
In my installation, I copied gremlin-server.properties into gremlin-server-new.properties and included the path to the new database; I then extended the graphs-entry in in gremlin-server-yaml to include graph: ./config/gremlin-server-new.properties

It boots with:

2024-12-15 16:55:11.435 INFO  [ServerGremlinExecutor] A GraphTraversalSource is now bound to [g] with graphtraversalsource[arcadegraph[new], standard]

2024-12-15 16:55:11.438 INFO  [ServerGremlinExecutor] A GraphTraversalSource is now bound to [graph] with graphtraversalsource[arcadegraph[new], standard]

Access fails with The traversal source [new] for alias [g] is not configured on the server.

Edit2.
From the documentation:

> By default, the database "graph" will be available through the Gremlin Server. You can edit the database name or add more databases under the Gremlin Server by editing the file config/gremlin-server.groovy

I guess I'm in the wrong place, but I can't see what to change here?
