### DISCUSSION TITLE
Add extra environment variables to helm chart

### DISCUSSION THREAD

**Discussion by carlos-rodrigues-8x8** [ArcadeData/arcadedb#2306] [Ideas]
### What

The server.sh supports the customisation of the startup command throughout environment variables such as exec  `JAVA_OPTS`, `ARCADEDB_OPTS_MEMORY`, `JAVA_OPTS_SCRIPT`, `ARCADEDB_JMX`, `ARCADEDB_SETTINGS` and `ARCADEDB_HOME`, but using the helm charts we are not allowed to set the values for those variables. The idea is to create a mechanism to add environment to the helm templates.

### Why
This feature is particular useful if we need to customise different values for memory, jvm parameters or even different arcadedb settings.

### How
The propose is to add a new parameter `arcadedb.extraEnvironment`, which is a list of name/value where we can setup the environment name and values. e.g:

```
arcadedb:
  extraEnvironment:
    - name: ARCADEDB_OPTS_MEMORY
      value: -Xms512M -Xmx512M
```
