### ISSUE TITLE
Edge's aren't being deleted with vertices for large enough datasets.

### ISSUE THREAD

**Issue by WSaffery** [ArcadeData/arcadedb#1626]
### ArcadeDB Version:

ArcadeDB Server v24.5.1

### OS and JDK Version:

Running on Linux 6.8.10-300.fc40.x86_64 - OpenJDK 64-Bit Server VM 17.0.11 ((Red_Hat-17.0.11.0.9-1))

### Expected behavior

Dropping vertices should always remove all edges.

### Actual behavior

While I've confirmed that generally dropping a vertex drops its edges. For the large dataset I am currently testing, dropping all vertices in one query fails to remove all edges.

I've tested this in both gremlin, and in SQL  using a node supertype.

```gremlin
g.V().drop()
```
and
```SQL
delete from `node`
```

The gremlin code has been tested via remote traversal and the web console, the SQL only via the console.

### Steps to reproduce

Load the attached database backup, attached [here](https://github.com/user-attachments/files/15602639/issueBackup.zip), and then run either `g.V().drop()` or `delete from node`

You may need to change your evaluationTimeout in `gremlin-server.yaml` to run `g.V().drop()` without timing out.
My last run in gremlin took 37454ms and my evaluationTimeout is at 120000 (ms).

Apologies I have been unable to easily determine a smaller subset of the database for which the problem persists. I did trim down my original dataset to just include the edge `isLocatedIn` to make the backup smaller.

My `gremlin-server.yaml` for posterity

```yaml
host: 0.0.0.0
evaluationTimeout: 120000
graphs:
  graph: ./config/gremlin-server.properties
scriptEngines:
  gremlin-groovy:
    plugins:
      org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {}
      org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin:
        classImports:
          - java.lang.Math
          - org.opencypher.gremlin.traversal.CustomFunctions
          - org.opencypher.gremlin.traversal.CustomPredicate
        methodImports:
          - "java.lang.Math#*"
          - "org.opencypher.gremlin.traversal.CustomPredicate#*"
          - "org.opencypher.gremlin.traversal.CustomFunctions#*"
      org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin:
        files:
          - ./config/gremlin-server.groovy
serializers:
  - className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1
    config:
      ioRegistries:
        - com.arcadedb.gremlin.io.ArcadeIoRegistry
  - className: org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV3
    config:
      ioRegistries:
        - com.arcadedb.gremlin.io.ArcadeIoRegistry
  - className: org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV2
    config:
      ioRegistries:
        - com.arcadedb.gremlin.io.ArcadeIoRegistry
processors:
  - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000 } }

```
