### ISSUE TITLE
Creating a database inside a docker image confirms it's created, but REST API refuses to list it in `list databases`

### ISSUE THREAD

**Issue by ExtReMLapin** [ArcadeData/arcadedb#2150]
There is something REALLY WEIRD going on.

Inside my docker, created partially like : 

```
RUN apt-get update && apt-get upgrade && apt-get install -y openjdk-21-jdk && rm -rf /var/lib/apt/lists/*

RUN rm -rf /opt/arcadedb/*
COPY arcade.zip /tmp/arcade.zip

RUN unzip /tmp/arcade.zip -d /opt/arcadedb  && \
    rm /tmp/arcade.zip

```

and

```yaml
version: "3.8"
services:
  arcadedb:
    image: idextend-rc7:latest
    working_dir: /opt/arcadedb/
    command: ./entrypoint.sh
    ports:
      - "2480:2480"
    volumes:
      - ./idextend_local/config.ini:/opt/idextend/config.ini
      - ./idextend_local/arcadedb/log/:/opt/arcadedb/log/
      - ./idextend_local/arcadedb/config/:/opt/arcadedb/config/
      - ./idextend_local/arcadedb/databases/:/opt/arcadedb/databases/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2480"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

```

`'list databases'` returns `[]`

` 'create database test1'` returns `ok`

re run `'list databases'` still returns `[]` but 

run again ` 'create database test1'` and it returns `Database 'test1' already exists`

https://github.com/user-attachments/assets/cddeb858-ef9c-4a4d-9309-67bc4d39b92e
