### ISSUE TITLE
Arcade does not start properly on M1 Mac

### ISSUE THREAD

**Issue by kai-baumann** [ArcadeData/arcadedb#408]
## Expected behavior
I wanted to start the docker image of arcadedb on an M1 Mac. The Image starts normally and I can access the studio with port 2480.

## Actual behavior
The image just fills the ram till the docker limit and gets killed by the oom killer (exit code 137).
I tried to build the image with an arm linux image. That was successful but when i tried to start the image it just prints that I need to set the root password or use the generated one. This message gets printed every second. Setting the env vars does not seem to change this behaviour.

I use the following compose file to start the arcadedb:
```
---
version: '3.7'
    arcadedb:
        image: arcadedata/arcadedb:22.2.1
        container_name: relate-arcade
        restart: 'no'
        environment:
            arcadedb.server.defaultDatabases: 'Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}'
            arcadedb.server.rootPassword: 'playwithdata'
        ports:
            - '127.0.0.1:2480:2480'
            - '127.0.0.1:2424:2424'
```

## Steps to reproduce
On an M1 Mac just use the docker compose file above. The ram gets filled and the application will be terminated with exit code 137.
