### ISSUE TITLE
Unresponsive Containers (Gremlin Warm Up - Execution Timeout)

### ISSUE THREAD

**Issue by psytron** [ArcadeData/arcadedb#795]
## Expected behavior
Server accessible on 2480

## Actual behavior
Timeouts
Studio inaccessible on port 2480
15-30 second queries from near empty database
Spontaneously ignoring all queries
Container hangs until reboot 
Container sometimes hangs during reboot is inaccessible

## Steps to reproduce
Just using it regularly. Until V22 it worked pretty reliably. Now we're a little worried about using it for real world use case. We love the idea of having Cypher and SQL models available in one DB. Is Docker still the recommended method of deploying?

**Comment by lvca** [comment]
Could you please post here the command you're using to run docker?

**Comment by psytron** [comment]
Docker command from main docs 
```
docker run --rm -p 2480:2480 -p 2424:2424
           -e arcadedb.server.rootPassword=playwithdata
           -e "arcadedb.server.defaultDatabases=OpenBeer[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}"
           arcadedata/arcadedb:latest
```

and also the same docker command from main docks as a  docker compose script 

```
version: "3.9"
services:
    arcade:
        image: arcadedata/arcadedb:latest
        ports:
            - 2480:2480  # host : container port
            - 2424:2424  # host : container port            
        environment:
            JAVA_OPTS: >
                -Darcadedb.server.rootPassword=playwithdata 
                -Darcadedb.dumpConfigAtStartup=true
                -Darcadedb.ha.enabled=true
            # -Darcadedb.server.defaultDatabases=Imported[root]{import:https://github.com/ArcadeData/arcadedb-datasets/raw/main/orientdb/OpenBeer.gz}
        restart: always
volumes:
    arcade_db_vol:

networks:
    default:
```
